steps:
  # Build the Docker image with correct build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'BUILD_VERSION=${BUILD_ID}'
      - '--build-arg'
      - 'VITE_DOMAIN=https://login.divine.video'
      - '--build-arg'
      - 'VITE_ALLOWED_PUBKEYS=89ef92b9ebe6dc1e4ea398f6477f227e95429627b0a33dc89b640e137b256be5,76c71aae3a491f1d9eec47cba17e229cda4113a0bbb6e6ae1776d7643e29cafa'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker/keycast:latest'
      - '.'
    timeout: 1200s

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker/keycast:latest'

  # Deploy to Cloud Run with hashring-enabled horizontal scaling
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'keycast'
      - '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/docker/keycast:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--timeout=300'
      - '--min-instances=3'
      - '--max-instances=100'
      - '--concurrency=80'
      - '--no-cpu-throttling'
      - '--execution-environment=gen2'
      - '--cpu-boost'
      - '--session-affinity'
      - '--startup-probe=httpGet.path=/health,httpGet.port=3000,initialDelaySeconds=5,periodSeconds=10,failureThreshold=30,timeoutSeconds=5'
      - '--liveness-probe=httpGet.path=/health,httpGet.port=3000,periodSeconds=30,timeoutSeconds=5,failureThreshold=3'
      - '--add-cloudsql-instances=openvine-co:us-central1:keycast-db'
      - '--set-secrets=DATABASE_URL=keycast-database-url:6,SERVER_NSEC=keycast-ucan-secret:latest,SENDGRID_API_KEY=keycast-sendgrid-api-key:latest'
      - '--set-env-vars=NODE_ENV=production,USE_GCP_KMS=true,GCP_PROJECT_ID=${PROJECT_ID},ALLOWED_ORIGINS=https://login.divine.video,APP_URL=https://login.divine.video,FROM_EMAIL=noreply@divine.video,RUST_LOG=info,ENABLE_EXAMPLES=true'

  # Smoke tests - verify deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "⏳ Waiting for service to be ready..."
        sleep 30

        SERVICE_URL=$$(gcloud run services describe keycast --region=us-central1 --format='value(status.url)')
        echo "Service URL: $$SERVICE_URL"

        echo "🔍 Testing API health endpoint..."
        if ! curl -f -s "$$SERVICE_URL/health"; then
          echo "❌ Health check failed"
          exit 1
        fi
        echo "✅ Health check passed"

        echo "🔍 Testing CORS preflight for /api/auth/register..."
        HTTP_CODE=$$(curl -s -o /dev/null -w "%{http_code}" \
          -H "Origin: https://login.divine.video" \
          -H "Access-Control-Request-Method: POST" \
          -H "Access-Control-Request-Headers: Content-Type" \
          -X OPTIONS \
          "$$SERVICE_URL/api/auth/register")

        if [ "$$HTTP_CODE" != "200" ]; then
          echo "❌ CORS preflight failed with HTTP $$HTTP_CODE"
          exit 1
        fi
        echo "✅ CORS preflight passed"

        echo "🎉 All smoke tests passed!"

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker/keycast:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 2400s
